import type { INodeProperties } from 'n8n-workflow';

export const dialogsDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['dialog'] } },
		options: [
			{ name: 'Close', value: 'close', action: 'Close dialog', description: 'Закрыть диалог' },
			{ name: 'Create', value: 'create', action: 'Create dialog', description: 'Создать новый диалог' },
			{ name: 'Get Details', value: 'getDetails', action: 'Get dialog details', description: 'Получить подробную информацию о диалоге' },
			{ name: 'Get Group Clients', value: 'getGroupClients', action: 'Get group dialog clients', description: 'Получить список клиентов группового диалога' },
			{ name: 'List', value: 'list', action: 'List dialogs', description: 'Получить список диалогов' },
			{ name: 'Mark Answered', value: 'markAnswered', action: 'Mark dialog answered', description: 'Отметить диалог как отвеченный' },
			{ name: 'Mark Seen', value: 'markSeen', action: 'Mark dialog seen', description: 'Отметить диалог как просмотренный' },
			{ name: 'Mark Unanswered', value: 'markUnanswered', action: 'Mark dialog unanswered', description: 'Отметить диалог как неотвеченный' },
			{ name: 'Set Operator', value: 'setOperator', action: 'Set operator for dialog', description: 'Назначить оператора для диалога' },
		],
		default: 'list',
	},
	{
		displayName: 'Page',
		name: 'page',
		type: 'number',
		default: 1,
		typeOptions: { minValue: 1 },
		description: 'Номер страницы',
		displayOptions: { show: { resource: ['dialog'], operation: ['list'] } },
	},
	{
		displayName: 'Page Size',
		name: 'pageSize',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 500 },
		description: 'Количество элементов на странице',
		displayOptions: { show: { resource: ['dialog'], operation: ['list'] } },
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'All', value: 'all' },
			{ name: 'Open', value: 'open' },
			{ name: 'Close', value: 'close' },
		],
		default: 'all',
		description: 'Статус диалогов для выборки',
		displayOptions: { show: { resource: ['dialog'], operation: ['list'] } },
	},
	{
		displayName: 'Channel ID',
		name: 'channelId',
		type: 'string',
		default: '',
		description: 'Необязательный фильтр по ID канала',
		displayOptions: { show: { resource: ['dialog'], operation: ['list'] } },
	},
	{
		displayName: 'Channel Type',
		name: 'channelType',
		type: 'string',
		default: '',
		placeholder: 'whatsapp',
		description: 'Необязательный фильтр по типу канала',
		displayOptions: { show: { resource: ['dialog'], operation: ['list'] } },
	},
	{
		displayName: 'Dialog ID',
		name: 'dialogId',
		type: 'string',
		required: true,
		default: '',
		description: 'Идентификатор диалога',
		displayOptions: {
			show: {
				resource: ['dialog'],
				operation: ['getDetails', 'getGroupClients', 'close', 'markSeen', 'setOperator', 'markAnswered', 'markUnanswered'],
			},
		},
	},
	{
		displayName: 'Operator ID',
		name: 'operatorId',
		type: 'string',
		required: true,
		default: '',
		description: 'Идентификатор оператора',
		displayOptions: { show: { resource: ['dialog'], operation: ['setOperator'] } },
	},
	{
		displayName: 'Channel ID',
		name: 'createChannelId',
		type: 'string',
		required: true,
		default: '',
		description: 'Идентификатор канала для нового диалога',
		displayOptions: { show: { resource: ['dialog'], operation: ['create'] } },
	},
	{
		displayName: 'Client Phone',
		name: 'createClientPhone',
		type: 'string',
		default: '',
		placeholder: '+79161234567',
		description: 'Телефон клиента для создания диалога',
		displayOptions: { show: { resource: ['dialog'], operation: ['create'] } },
	},
	{
		displayName: 'Client Email',
		name: 'createClientEmail',
		type: 'string',
		default: '',
		placeholder: 'client@example.com',
		description: 'Email клиента для создания диалога',
		displayOptions: { show: { resource: ['dialog'], operation: ['create'] } },
	},
];
